version: "3.9"

services:
  postgres:
    image: postgres:14.1-alpine
    volumes:
      - ./postgres/data:/var/lib/postgres/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    command: -p ${POSTGRES_PORT}
